[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/status"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[services]]
name = "clamm-ponder-v2" 